DM-30895: Move AssembleCoaddTask and its children to drp_tasks
lsst/drp_tasks pull request #26
Opened 2023-09-13 14:41 UTC by arunkannawadi

2023-09-13 16:14 UTC, fred3m requested changes
Just a few small comments and corrections.

2023-09-13 16:14 UTC, fred3m commented on python/lsst/drp/tasks/assemble_coadd.py
> +                yield subBBox
This is in `lsst.pipe.tasks.coaddBase`, so it can be removed as a static method of this class.

2023-09-19 19:47 UTC, arunkannawadi commented
Great catches, Fred! I've addressed the comments now.

 - [ ] Move assembleChi2Coadd.py
 - [ ] Remove the subBBoxIter static method (and use the one from coaddBase)
 - [ ]  Add a period of kernel in a docstring

2023-09-19 20:58 UTC, fred3m approved these changes

2023-09-20 04:01 UTC, merged